// THIS FILE IS COMPLETELY GENERATED BY AI. I JUST WANTED TO GET AN IDEA OF WHAT IT WOULD LOOK LIKE AND HOW IT FOULD FIT INTO ALL THE PATTERNS. WE SHOULD NOT USE IT.

#include "EmergencyOperationsDesk.h"
#include "CampusControlRoom.h"       // Concrete Mediator
#include "SecurityTeam.h"            // Concrete Colleague/Receiver
#include "AccessControlService.h"    // Concrete Colleague/Receiver
#include "MunicipalServiceAdapter.h" // Concrete Adapter
#include "SecureArea.h"              // Concrete Command
#include "DispatchUnit.h"            // Concrete Command
#include <iostream>

EmergencyOperationsDesk::EmergencyOperationsDesk()
{
    // 1. Initialize the Mediator and Invoker
    mediator = new CampusControlRoom();
    console = new OperatorConsole();

    // 2. Initialize the Receivers and link them to the Mediator
    securityTeam = new SecurityTeam(mediator, "Sec-Alpha", 10, false);
    accessControl = new AccessControlService(mediator, "Campus-Gates"); // Assuming you build this

    // 3. Initialize the Adapter
    municipalAdapter = new MunicipalServiceAdapter();
}

EmergencyOperationsDesk::~EmergencyOperationsDesk()
{
    // Delete in reverse order of creation to satisfy Valgrind
    delete municipalAdapter;
    delete accessControl;
    delete securityTeam;
    delete console;
    delete mediator;
}

void EmergencyOperationsDesk::triggerCampusLockdown()
{
    std::cout << "\n=== FACADE: INITIATING CAMPUS LOCKDOWN ===\n";

    // Step 1: Act as the Command Client[cite: 7]
    // Instantiate the concrete commands and assign their receivers
    ResponseAction *secureCommand = new SecureArea(accessControl);
    ResponseAction *dispatchCommand = new DispatchUnit(securityTeam);

    std::cout << "[Desk] Routing commands through Operator Console...\n";
    // The Invoker handles executing and storing the commands (for the Memento undo)
    console->executeCommand(secureCommand);
    console->executeCommand(dispatchCommand);

    // Step 2: Act as the Adapter Client[cite: 7]
    // Trigger legacy/external behavior seamlessly
    std::cout << "[Desk] Contacting municipal authorities via Adapter...\n";
    municipalAdapter->dispatchCityPolice();

    std::cout << "=== FACADE: LOCKDOWN WORKFLOW COMPLETE ===\n\n";
}